[package]
name = "potato-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
scanf = "1.2.1"
sha1 = "0.10.1"
rand = "0.8.5"
home = "0.5.9"

[profile.release]
codegen-untis = 1
lto = "fat"
panic = "abort"
strip = "debuginfo"

[build]
rustflags = ["-C", "target-cpu=native"]
