[package]
name = "potodo"
version = "0.1.0"
edition = "2021"

[dependencies]
scanf = "1.2.1"
sha1 = "0.10.1"
rand = "0.8.5"
home = "0.5.9"
ratatui = "0.25.0"
crossterm = "0.27.0"
tui-textarea = "0.4.0"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "debuginfo"
